In [1]:
import numpy as np

In [2]:
import pandas as pd 

In [3]:
arr= np.array([12,13,14,15,18,19,21,23,22])
arr

array([12, 13, 14, 15, 18, 19, 21, 23, 22])

In [4]:
arr1= np.array([12,45.5,True,'hi'])

In [5]:
arr1

array(['12', '45.5', 'True', 'hi'], dtype='<U32')

In [6]:
# arrays - shape 1d, 2d, 3d

In [9]:
arr.ndim  # number of dimensions 

1

In [10]:
arr2= np.array([[1,2,3,4,5]])
arr2

array([[1, 2, 3, 4, 5]])

In [11]:
arr2.ndim

2

In [13]:
arr3= np.array([[1,2,3],[4,5,6],[6,7,8]])
arr3

array([[1, 2, 3],
       [4, 5, 6],
       [6, 7, 8]])

In [14]:
arr3.ndim

2

In [15]:
# 3d

In [16]:
arr4= np.array([
    [
        [1,2],
        [3,4]
    ],
    [
        [5,6],
        [7,8]
    ]
])

In [17]:
arr4

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [18]:
arr4.ndim

3

In [19]:
arr4.shape

(2, 2, 2)

In [20]:
arr.shape

(9,)

In [21]:
arr3.shape

(3, 3)

In [22]:
arr

array([12, 13, 14, 15, 18, 19, 21, 23, 22])

In [24]:
arr.sum()

157

In [25]:
arr3

array([[1, 2, 3],
       [4, 5, 6],
       [6, 7, 8]])

In [26]:
arr3.sum()

42

In [28]:
arr3.sum(axis=0)  # axis 0 means rows, axis 1 means columns 

array([11, 14, 17])

In [29]:
arr3.sum(axis=1)

array([ 6, 15, 21])

In [37]:
ide= np.identity(6)
ide

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [40]:
ide.reshape(4,9)

array([[1., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 1.]])

In [41]:
#update 

In [42]:
arr

array([12, 13, 14, 15, 18, 19, 21, 23, 22])

In [43]:
arr[4]

18

In [44]:
arr[4]=100

In [45]:
arr

array([ 12,  13,  14,  15, 100,  19,  21,  23,  22])

In [46]:
arr3

array([[1, 2, 3],
       [4, 5, 6],
       [6, 7, 8]])

In [49]:
arr3[1][1]

5

In [52]:
arr3[2][1]

7

In [53]:
arr3[2][1]=12

In [54]:
arr3

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 6, 12,  8]])

In [55]:
arr4

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [58]:
arr4[0][1][1]

4

In [59]:
np.zeros(4)

array([0., 0., 0., 0.])

In [60]:
np.ones(3)

array([1., 1., 1.])

In [61]:
#arange

In [66]:
a= np.arange(4,33,2) # start stop step 

In [67]:
a.shape

(15,)

In [69]:
a

array([ 4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32])

In [68]:
a.reshape(3,5)

array([[ 4,  6,  8, 10, 12],
       [14, 16, 18, 20, 22],
       [24, 26, 28, 30, 32]])

In [73]:
a.reshape(3,1,5)

array([[[ 4,  6,  8, 10, 12]],

       [[14, 16, 18, 20, 22]],

       [[24, 26, 28, 30, 32]]])

In [74]:
a.reshape(3,5,1)

array([[[ 4],
        [ 6],
        [ 8],
        [10],
        [12]],

       [[14],
        [16],
        [18],
        [20],
        [22]],

       [[24],
        [26],
        [28],
        [30],
        [32]]])

In [77]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [78]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [79]:
arr3

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 6, 12,  8]])

In [80]:
arr5=np.array([
    [1,2,4],
    [4,5,6],
    [9,8,7]
])
arr5

array([[1, 2, 4],
       [4, 5, 6],
       [9, 8, 7]])

In [81]:
arr3+arr5

array([[ 2,  4,  7],
       [ 8, 10, 12],
       [15, 20, 15]])

In [82]:
arr5

array([[1, 2, 4],
       [4, 5, 6],
       [9, 8, 7]])

In [83]:
arr5.max()

9

In [84]:
arr5.min()

1

In [85]:
arr5.argmax()

6

In [86]:
arr5.argmin()

0

In [87]:
arr

array([ 12,  13,  14,  15, 100,  19,  21,  23,  22])

In [88]:
arr1= np.array([90,45,67])
arr1

array([90, 45, 67])

In [90]:
np.concatenate((arr, arr1))

array([ 12,  13,  14,  15, 100,  19,  21,  23,  22,  90,  45,  67])

In [91]:
arr10=np.array([34,0,56,78,90,0])
arr10

array([34,  0, 56, 78, 90,  0])

In [92]:
np.nonzero(arr10)

(array([0, 2, 3, 4], dtype=int64),)